-module(ews_emit_SUITE).
-include_lib("common_test/include/ct.hrl").

%%TODO header should be inside of include, but we need to rename the git repo
%%to ews first
-include("../src/ews.hrl").
-include_lib("ews/include/ews.hrl").

%% CT functions
-export([suite/0, groups/0, all/0,
         init_per_suite/1, end_per_suite/1,
         init_per_testcase/2, end_per_testcase/2]).

%% Tests
-export([empty_table/1,
         simple_graph/1,
         simple_circular_graph/1,
         circular_graph/1,
         documented_graph/1,
         enum_value_docs/1,
         list_of_enums/1,
         unaliased_type_fails/1
        ]).

suite() -> [{timetrap, {seconds, 20}}].

groups() ->
    [{emit_test, [shuffle],
      [empty_table,
       simple_graph,
       simple_circular_graph,
       circular_graph,
       documented_graph,
       enum_value_docs,
       list_of_enums,
       unaliased_type_fails
      ]}].

all() ->
    [{group, emit_test}].

init_per_suite(Config) ->
    ews:start(),
    Config.

end_per_suite(_Config) ->
    ok.

init_per_testcase(_Testcase, Config) ->
    Config.

end_per_testcase(_TestCase, Config) ->
    Config.

empty_table(Config) ->
    Table = ets:new(empty_table, []),
    Model = #model{type_map=Table},
    Filename = emit_file(Config),
    ews_emit:model_to_file(Model, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    <<"%% Generated by ews from the WSDL and XSD files of the test\n"
      "%% model. Do not edit it by hand: regenerate it instead.\n">> = Bin,
    ok.

simple_graph(Config) ->
    Table = ets:new(type_table, []),
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"},
                            alias = t1,
                            elems =
                                [#elem{qname = {"ns", "e1"},
                                       type = int_type(),
                                       meta = meta(undefined, 0, 1)},
                                 #elem{qname = {"ns", "e2"},
                                       type = string_type(),
                                       meta = meta("true", 0, 1)}]}}),
    Model = #model{type_map=Table},
    Filename = emit_file(Config),
    ews_emit:model_to_file(Model, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    Expected = <<"%% {\"ns\", \"t1\"}\n"
                 "-record(t1, {e1 :: integer() | undefined,\n"
                 "             e2 :: binary() | string() | nil | undefined})."
                 "\n">>,
    H = header(),
    Bin = <<H/binary, Expected/binary>>,
    ok.

simple_circular_graph(Config) ->
    Table = ets:new(type_table, []),
    ews_alias:create_unique({"ns", "t1"}, test),
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"},
                            alias = t1,
                            elems =
                                [#elem{qname = {"ns", "e1"},
                                       type = {"ns", "t1"},
                                       meta = meta(undefined, 0, 1)}]}}),
    Model = #model{type_map=Table},
    Filename = emit_file(Config),
    ews_emit:model_to_file(Model, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    Expected = <<"%% {\"ns\", \"t1\"}\n"
                 "-record(t1, {e1 :: #t1{} | undefined}).\n">>,
    H = header(),
    Bin = <<H/binary, Expected/binary>>,
    ok.

circular_graph(Config) ->
    Table = ets:new(type_table, []),
    ews_alias:create_unique({"ns", "t1"}, test),
    ews_alias:create_unique({"ns", "t2"}, test),
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"},
                            alias = t1,
                            elems =
                                [#elem{qname = {"ns", "t1e1"},
                                       type = {"ns", "t2"},
                                       meta = meta(undefined, 0, 1)}]}}),
    ets:insert(Table, {{"ns", "t2"},
                       #type{qname={"ns", "t2"},
                            alias = t2,
                            elems =
                                [#elem{qname = {"ns", "t2e1"},
                                       type = {"ns", "t1"},
                                       meta = meta(undefined, 0, 1)}]}}),
    Model = #model{type_map=Table},
    Filename = emit_file(Config),
    ews_emit:model_to_file(Model, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    H = header(),
    B1 = <<H/binary,
           "%% {\"ns\", \"t1\"}\n"
           "-type '#t1'() :: tuple().  %% Needed due to circular type definition\n\n"
           "%% {\"ns\", \"t2\"}\n"
           "-record(t2, {t2e1 :: '#t1'() | undefined}).\n\n"
           "%% {\"ns\", \"t1\"}\n"
           "-record(t1, {t1e1 :: #t2{} | undefined}).\n">>,
    B2 = <<H/binary,
           "%% {\"ns\", \"t2\"}\n"
           "-type '#t2'() :: tuple().  %% Needed due to circular type definition\n\n"
           "%% {\"ns\", \"t1\"}\n"
           "-record(t1, {t1e1 :: '#t2'() | undefined}).\n\n"
           "%% {\"ns\", \"t2\"}\n"
           "-record(t2, {t2e1 :: #t1{} | undefined}).\n">>,
    case Bin of
        B1 -> ok;
        B2 -> ok;
        _ -> ct:fail({unexpected_output, Bin})
    end,
    ok.

%% <documentation> from the XSD becomes comments: on the record for the type's
%% own annotation, and above the field for the element's. It is free text, so
%% it wraps, and the wrapped lines line up under the field they document.
documented_graph(Config) ->
    Table = ets:new(type_table, []),
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"},
                             alias = t1,
                             doc = <<"What the type is for.">>,
                             elems =
                                 [#elem{qname = {"ns", "e1"},
                                        type = int_type(),
                                        doc = <<"Why this field exists, at "
                                                "enough length that it has to "
                                                "wrap onto a second line.">>,
                                        meta = meta(undefined, 0, 1)},
                                  #elem{qname = {"ns", "e2"},
                                        type = string_type(),
                                        meta = meta(undefined, 1, 1)}]}}),
    Model = #model{type_map=Table},
    Filename = emit_file(Config),
    ews_emit:model_to_file(Model, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    Expected =
        <<"%% {\"ns\", \"t1\"}\n"
          "%% What the type is for.\n"
          "-record(t1, {%% Why this field exists, at enough length that it has "
          "to wrap\n"
          "             %% onto a second line.\n"
          "             e1 :: integer() | undefined,\n"
          "             e2 :: binary() | string()}).\n">>,
    H = header(),
    Bin = <<H/binary, Expected/binary>>,
    ok.

%% Common Test gives each case a private directory; the generated file belongs
%% there rather than in whatever directory the suite happened to run from.
emit_file(Config) ->
    filename:join(proplists:get_value(priv_dir, Config), "emitted.hrl").

%% Every generated file starts with this; there is no timestamp in it, so a
%% regenerated file is byte-identical when the model has not changed.
header() ->
    <<"%% Generated by ews from the WSDL and XSD files of the test\n"
      "%% model. Do not edit it by hand: regenerate it instead.\n\n">>.

%% What an enumeration's values mean has nowhere of its own to go in the
%% generated file, so it is listed under each field typed by it, indented so a
%% value needing more than one line cannot be read as several values.
enum_value_docs(Config) ->
    Table = ets:new(type_table, []),
    Enum = #enum{type = string_type(),
                 values = [{open, "open"}, {closed, "closed"}],
                 value_docs = [{"open", <<"Still being worked on, and said "
                                          "at enough length that it has to "
                                          "wrap.">>},
                               {"closed", <<"Done with.">>}]},
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"}, alias = t1,
                             elems = [#elem{qname = {"ns", "e1"},
                                            type = Enum,
                                            meta = meta(undefined, 1, 1)}]}}),
    Filename = emit_file(Config),
    ews_emit:model_to_file(#model{type_map=Table}, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    H = header(),
    Expected = <<"%% {\"ns\", \"t1\"}\n"
                 "-record(t1, {%% open: Still being worked on, and said at "
                 "enough length\n"
                 "             %%   that it has to wrap.\n"
                 "             %% closed: Done with.\n"
                 "             e1 :: open\n"
                 "                 | closed}).\n">>,
    Bin = <<H/binary, Expected/binary>>,
    ok.

%% A repeated enum is spelled as a list, and the bracket has to be laid out so
%% that the values still line up under each other.
list_of_enums(Config) ->
    Table = ets:new(type_table, []),
    Enum = #enum{type = string_type(), values = [{sms, "sms"},
                                                 {e_mail, "eMail"}]},
    One = #enum{type = string_type(), values = [{sms, "sms"}]},
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"}, alias = t1,
                             elems = [#elem{qname = {"ns", "e1"},
                                            type = Enum,
                                            meta = meta(undefined, 0, 2)},
                                      #elem{qname = {"ns", "e2"},
                                            type = Enum,
                                            meta = meta(undefined, 1, 1)},
                                      #elem{qname = {"ns", "e3"},
                                            type = One,
                                            meta = meta(undefined, 1, 2)}]}}),
    Filename = emit_file(Config),
    ews_emit:model_to_file(#model{type_map=Table}, Filename, test),
    {ok, Bin} = file:read_file(Filename),
    H = header(),
    %% e1 is a list, so the bracket shares a column with the pipe under it and
    %% both values share one too. e2 is not a list. e3 is a list with a single
    %% value, where there is nothing to line up and no space is wanted.
    Expected = <<"%% {\"ns\", \"t1\"}\n"
                 "-record(t1, {e1 :: [ sms\n"
                 "                   | e_mail] | undefined,\n"
                 "             e2 :: sms\n"
                 "                 | e_mail,\n"
                 "             e3 :: [sms]}).\n">>,
    Bin = <<H/binary, Expected/binary>>,
    ok.

%% A type the model cannot name would have been written as #false{}, a record
%% no one declared: the file would not compile and the error would point far
%% from the cause. Emitting says which type of which model it could not name
%% instead.
unaliased_type_fails(Config) ->
    Table = ets:new(type_table, []),
    %% In the table, so the dependency walk resolves it, but never registered
    %% with ews_alias for this model -- which is what a second model sharing
    %% the type used to leave behind.
    Unaliased = {"ns", "unaliased"},
    ets:insert(Table, {Unaliased,
                       #type{qname = Unaliased, alias = unaliased,
                             elems = []}}),
    ets:insert(Table, {{"ns", "t1"},
                       #type{qname={"ns", "t1"}, alias = t1,
                             elems = [#elem{qname = {"ns", "e1"},
                                            type = Unaliased,
                                            meta = meta(undefined, 1, 1)}]}}),
    Filename = emit_file(Config),
    {error, {no_alias_for_type, Unaliased, test}} =
        try ews_emit:model_to_file(#model{type_map=Table}, Filename, test) of
            Unexpected -> {emitted, Unexpected}
        catch
            error:Reason -> {error, Reason}
        end,
    ok.

int_type() ->
    #base{xsd_type = {"http://www.w3.org/2001/XMLSchema","int"},
          erl_type = integer,
          list = false,
          union = false}.

string_type() ->
    #base{xsd_type = {"http://www.w3.org/2001/XMLSchema","string"},
          erl_type = string,
          list = false,
          union = false}.

meta(Nillable, Min, Max) ->
    #meta{nillable = Nillable, min = Min, max = Max}.
