name: "Configure SSH key"
description: "Configure SSH key to be able to pull dependencies from Kivra's private GitHub repositories"
inputs:
  ssh_key:
    required: true
    description: An ssh key.
  ssh_auth_sock:
    description: Path to the ssh agent socket
    required: false
    default: "/tmp/ssh_agent.sock"
runs:
  using: "composite"
  steps:
    - run: |
        echo "SSH_AUTH_SOCK=${{ inputs.ssh_auth_sock }}" >> $GITHUB_ENV
        mkdir -p ${HOME}/.ssh
        ssh-agent -a ${{ inputs.ssh_auth_sock }} > /dev/null
        SSH_AUTH_SOCK=${{ inputs.ssh_auth_sock }} ssh-add - <<< "${{ inputs.ssh_key }}"
      shell: bash
