name: Automatic testing
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  OTP_VERSION: "28.3.1"
  REBAR3_VERSION: "3.26.0"

jobs:
  versioner:
    runs-on:
      group: arm-runners
    permissions:
      contents: write
      packages: write
    outputs:
      releaseTag: ${{ steps.semver.outputs.nextStrict }}
      commitTag: ${{ steps.git.outputs.commitTag }}
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # Need all to see past tags for semver

      - name: Calculate Semantic Version
        id: semver
        # this decides if we will tag a release
        if: github.ref_name == github.event.repository.default_branch && !startsWith(github.event.head_commit.message, 'no-release')
        uses: ietf-tools/semver-action@c90370b2958652d71c06a3484129a4d423a6d8a8 # v1
        with:
          token: ${{ github.token }}
          branch: master
          patchAll: true
          noVersionBumpBehavior: patch

      - name: Calculate Git Version
        id: git
        run: |
          GIT_BRANCH="${GITHUB_REF##*/}"
          GIT_COMMIT="${GITHUB_SHA:0:7}"
          echo "commitTag=${GIT_BRANCH}-${GIT_COMMIT}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: ${{ steps.semver.outputs.nextStrict != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.semver.outputs.nextStrict }}" --generate-notes

  compile-deps:
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch dependencies from cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            _build/*/*/*
            ebin
          key: deps-v1-${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.REBAR3_VERSION }}-${{ hashFiles('rebar.*') }}
      - name: Compile deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: rebar3 as test compile --deps_only

  compile:
    needs: [compile-deps]
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch dependencies from cache
        uses: actions/cache@v3
        id: cached-deps
        with:
          path: |
            _build/*/*/*
            ebin
          key: deps-v1-${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.REBAR3_VERSION }}-${{ hashFiles('rebar.*') }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Compile
        run: rebar3 as test compile

  xref:
    needs: [compile]
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run xref
        run: rebar3 xref

  ct:
    needs: [compile]
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run CT tests
        run: rebar3 ct

  eunit:
    needs: [compile]
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
           _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run EUnit tests
        run: rebar3 eunit

  dialyzer:
    needs: [compile]
    runs-on:
      group: arm-runners
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Configure SSH key
        uses: ./.github/actions/configure-ssh-key
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-dialyzer-${{ github.ref }}
          restore-keys:
            workspace-${{ github.ref }}
      - name: Run Dialyzer
        run: rebar3 dialyzer
